-- Seed 24 hours of sensor data for bathrooms: A-03, A-11, C-05, D-06
-- (B-04 excluded as requested)
-- All values are in percentage (0-100%)
-- Fixed deterministic values for consistent data collection
-- This simulates realistic sensor readings from hardware devices
--
-- IMPORTANT: Make sure bathrooms A-03, A-11, C-05, D-06 exist in the bathrooms table before running this!
-- Run this in Supabase SQL Editor with service role or admin privileges

-- Fixed deterministic data patterns for each hour (0-23)
-- Format: Hour, Gas%, Water%, Humidity%
-- [0, 12, 85, 45], [1, 15, 82, 48], [2, 18, 80, 52], [3, 20, 78, 55],
-- [4, 22, 75, 58], [5, 25, 88, 50], [6, 28, 92, 48], [7, 30, 95, 45],
-- [8, 28, 90, 42], [9, 25, 88, 40], [10, 22, 85, 38], [11, 20, 82, 35],
-- [12, 18, 80, 32], [13, 15, 78, 30], [14, 12, 75, 28], [15, 10, 72, 30],
-- [16, 12, 70, 32], [17, 15, 75, 35], [18, 18, 80, 38], [19, 20, 85, 42],
-- [20, 22, 88, 45], [21, 25, 90, 48], [22, 28, 85, 50], [23, 30, 82, 52]

BEGIN;

-- Delete existing sensor readings from the past 24 hours for these bathrooms
DELETE FROM sensor_readings
WHERE bathroom_id IN ('A-03', 'A-11', 'C-05', 'D-06')
AND created_at >= (NOW() - INTERVAL '24 hours');

-- Insert 24 hours of sensor data for A-03
INSERT INTO sensor_readings (bathroom_id, sensor_type, gas_type, value, unit, created_at) VALUES
('A-03', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '23 hours'),
('A-03', 'water', NULL, 85, '%', NOW() - INTERVAL '23 hours'),
('A-03', 'humidity', NULL, 45, '%', NOW() - INTERVAL '23 hours'),
('A-03', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '22 hours'),
('A-03', 'water', NULL, 82, '%', NOW() - INTERVAL '22 hours'),
('A-03', 'humidity', NULL, 48, '%', NOW() - INTERVAL '22 hours'),
('A-03', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '21 hours'),
('A-03', 'water', NULL, 80, '%', NOW() - INTERVAL '21 hours'),
('A-03', 'humidity', NULL, 52, '%', NOW() - INTERVAL '21 hours'),
('A-03', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '20 hours'),
('A-03', 'water', NULL, 78, '%', NOW() - INTERVAL '20 hours'),
('A-03', 'humidity', NULL, 55, '%', NOW() - INTERVAL '20 hours'),
('A-03', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '19 hours'),
('A-03', 'water', NULL, 75, '%', NOW() - INTERVAL '19 hours'),
('A-03', 'humidity', NULL, 58, '%', NOW() - INTERVAL '19 hours'),
('A-03', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '18 hours'),
('A-03', 'water', NULL, 88, '%', NOW() - INTERVAL '18 hours'),
('A-03', 'humidity', NULL, 50, '%', NOW() - INTERVAL '18 hours'),
('A-03', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '17 hours'),
('A-03', 'water', NULL, 92, '%', NOW() - INTERVAL '17 hours'),
('A-03', 'humidity', NULL, 48, '%', NOW() - INTERVAL '17 hours'),
('A-03', 'gas', 'H2S', 30, '%', NOW() - INTERVAL '16 hours'),
('A-03', 'water', NULL, 95, '%', NOW() - INTERVAL '16 hours'),
('A-03', 'humidity', NULL, 45, '%', NOW() - INTERVAL '16 hours'),
('A-03', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '15 hours'),
('A-03', 'water', NULL, 90, '%', NOW() - INTERVAL '15 hours'),
('A-03', 'humidity', NULL, 42, '%', NOW() - INTERVAL '15 hours'),
('A-03', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '14 hours'),
('A-03', 'water', NULL, 88, '%', NOW() - INTERVAL '14 hours'),
('A-03', 'humidity', NULL, 40, '%', NOW() - INTERVAL '14 hours'),
('A-03', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '13 hours'),
('A-03', 'water', NULL, 85, '%', NOW() - INTERVAL '13 hours'),
('A-03', 'humidity', NULL, 38, '%', NOW() - INTERVAL '13 hours'),
('A-03', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '12 hours'),
('A-03', 'water', NULL, 82, '%', NOW() - INTERVAL '12 hours'),
('A-03', 'humidity', NULL, 35, '%', NOW() - INTERVAL '12 hours'),
('A-03', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '11 hours'),
('A-03', 'water', NULL, 80, '%', NOW() - INTERVAL '11 hours'),
('A-03', 'humidity', NULL, 32, '%', NOW() - INTERVAL '11 hours'),
('A-03', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '10 hours'),
('A-03', 'water', NULL, 78, '%', NOW() - INTERVAL '10 hours'),
('A-03', 'humidity', NULL, 30, '%', NOW() - INTERVAL '10 hours'),
('A-03', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '9 hours'),
('A-03', 'water', NULL, 75, '%', NOW() - INTERVAL '9 hours'),
('A-03', 'humidity', NULL, 28, '%', NOW() - INTERVAL '9 hours'),
('A-03', 'gas', 'H2S', 10, '%', NOW() - INTERVAL '8 hours'),
('A-03', 'water', NULL, 72, '%', NOW() - INTERVAL '8 hours'),
('A-03', 'humidity', NULL, 30, '%', NOW() - INTERVAL '8 hours'),
('A-03', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '7 hours'),
('A-03', 'water', NULL, 70, '%', NOW() - INTERVAL '7 hours'),
('A-03', 'humidity', NULL, 32, '%', NOW() - INTERVAL '7 hours'),
('A-03', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '6 hours'),
('A-03', 'water', NULL, 75, '%', NOW() - INTERVAL '6 hours'),
('A-03', 'humidity', NULL, 35, '%', NOW() - INTERVAL '6 hours'),
('A-03', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '5 hours'),
('A-03', 'water', NULL, 80, '%', NOW() - INTERVAL '5 hours'),
('A-03', 'humidity', NULL, 38, '%', NOW() - INTERVAL '5 hours'),
('A-03', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '4 hours'),
('A-03', 'water', NULL, 85, '%', NOW() - INTERVAL '4 hours'),
('A-03', 'humidity', NULL, 42, '%', NOW() - INTERVAL '4 hours'),
('A-03', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '3 hours'),
('A-03', 'water', NULL, 88, '%', NOW() - INTERVAL '3 hours'),
('A-03', 'humidity', NULL, 45, '%', NOW() - INTERVAL '3 hours'),
('A-03', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '2 hours'),
('A-03', 'water', NULL, 90, '%', NOW() - INTERVAL '2 hours'),
('A-03', 'humidity', NULL, 48, '%', NOW() - INTERVAL '2 hours'),
('A-03', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '1 hour'),
('A-03', 'water', NULL, 85, '%', NOW() - INTERVAL '1 hour'),
('A-03', 'humidity', NULL, 50, '%', NOW() - INTERVAL '1 hour'),
('A-03', 'gas', 'H2S', 30, '%', NOW()),
('A-03', 'water', NULL, 82, '%', NOW()),
('A-03', 'humidity', NULL, 52, '%', NOW());

-- Insert 24 hours of sensor data for A-11
INSERT INTO sensor_readings (bathroom_id, sensor_type, gas_type, value, unit, created_at) VALUES
('A-11', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '23 hours'),
('A-11', 'water', NULL, 85, '%', NOW() - INTERVAL '23 hours'),
('A-11', 'humidity', NULL, 45, '%', NOW() - INTERVAL '23 hours'),
('A-11', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '22 hours'),
('A-11', 'water', NULL, 82, '%', NOW() - INTERVAL '22 hours'),
('A-11', 'humidity', NULL, 48, '%', NOW() - INTERVAL '22 hours'),
('A-11', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '21 hours'),
('A-11', 'water', NULL, 80, '%', NOW() - INTERVAL '21 hours'),
('A-11', 'humidity', NULL, 52, '%', NOW() - INTERVAL '21 hours'),
('A-11', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '20 hours'),
('A-11', 'water', NULL, 78, '%', NOW() - INTERVAL '20 hours'),
('A-11', 'humidity', NULL, 55, '%', NOW() - INTERVAL '20 hours'),
('A-11', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '19 hours'),
('A-11', 'water', NULL, 75, '%', NOW() - INTERVAL '19 hours'),
('A-11', 'humidity', NULL, 58, '%', NOW() - INTERVAL '19 hours'),
('A-11', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '18 hours'),
('A-11', 'water', NULL, 88, '%', NOW() - INTERVAL '18 hours'),
('A-11', 'humidity', NULL, 50, '%', NOW() - INTERVAL '18 hours'),
('A-11', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '17 hours'),
('A-11', 'water', NULL, 92, '%', NOW() - INTERVAL '17 hours'),
('A-11', 'humidity', NULL, 48, '%', NOW() - INTERVAL '17 hours'),
('A-11', 'gas', 'H2S', 30, '%', NOW() - INTERVAL '16 hours'),
('A-11', 'water', NULL, 95, '%', NOW() - INTERVAL '16 hours'),
('A-11', 'humidity', NULL, 45, '%', NOW() - INTERVAL '16 hours'),
('A-11', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '15 hours'),
('A-11', 'water', NULL, 90, '%', NOW() - INTERVAL '15 hours'),
('A-11', 'humidity', NULL, 42, '%', NOW() - INTERVAL '15 hours'),
('A-11', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '14 hours'),
('A-11', 'water', NULL, 88, '%', NOW() - INTERVAL '14 hours'),
('A-11', 'humidity', NULL, 40, '%', NOW() - INTERVAL '14 hours'),
('A-11', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '13 hours'),
('A-11', 'water', NULL, 85, '%', NOW() - INTERVAL '13 hours'),
('A-11', 'humidity', NULL, 38, '%', NOW() - INTERVAL '13 hours'),
('A-11', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '12 hours'),
('A-11', 'water', NULL, 82, '%', NOW() - INTERVAL '12 hours'),
('A-11', 'humidity', NULL, 35, '%', NOW() - INTERVAL '12 hours'),
('A-11', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '11 hours'),
('A-11', 'water', NULL, 80, '%', NOW() - INTERVAL '11 hours'),
('A-11', 'humidity', NULL, 32, '%', NOW() - INTERVAL '11 hours'),
('A-11', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '10 hours'),
('A-11', 'water', NULL, 78, '%', NOW() - INTERVAL '10 hours'),
('A-11', 'humidity', NULL, 30, '%', NOW() - INTERVAL '10 hours'),
('A-11', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '9 hours'),
('A-11', 'water', NULL, 75, '%', NOW() - INTERVAL '9 hours'),
('A-11', 'humidity', NULL, 28, '%', NOW() - INTERVAL '9 hours'),
('A-11', 'gas', 'H2S', 10, '%', NOW() - INTERVAL '8 hours'),
('A-11', 'water', NULL, 72, '%', NOW() - INTERVAL '8 hours'),
('A-11', 'humidity', NULL, 30, '%', NOW() - INTERVAL '8 hours'),
('A-11', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '7 hours'),
('A-11', 'water', NULL, 70, '%', NOW() - INTERVAL '7 hours'),
('A-11', 'humidity', NULL, 32, '%', NOW() - INTERVAL '7 hours'),
('A-11', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '6 hours'),
('A-11', 'water', NULL, 75, '%', NOW() - INTERVAL '6 hours'),
('A-11', 'humidity', NULL, 35, '%', NOW() - INTERVAL '6 hours'),
('A-11', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '5 hours'),
('A-11', 'water', NULL, 80, '%', NOW() - INTERVAL '5 hours'),
('A-11', 'humidity', NULL, 38, '%', NOW() - INTERVAL '5 hours'),
('A-11', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '4 hours'),
('A-11', 'water', NULL, 85, '%', NOW() - INTERVAL '4 hours'),
('A-11', 'humidity', NULL, 42, '%', NOW() - INTERVAL '4 hours'),
('A-11', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '3 hours'),
('A-11', 'water', NULL, 88, '%', NOW() - INTERVAL '3 hours'),
('A-11', 'humidity', NULL, 45, '%', NOW() - INTERVAL '3 hours'),
('A-11', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '2 hours'),
('A-11', 'water', NULL, 90, '%', NOW() - INTERVAL '2 hours'),
('A-11', 'humidity', NULL, 48, '%', NOW() - INTERVAL '2 hours'),
('A-11', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '1 hour'),
('A-11', 'water', NULL, 85, '%', NOW() - INTERVAL '1 hour'),
('A-11', 'humidity', NULL, 50, '%', NOW() - INTERVAL '1 hour'),
('A-11', 'gas', 'H2S', 30, '%', NOW()),
('A-11', 'water', NULL, 82, '%', NOW()),
('A-11', 'humidity', NULL, 52, '%', NOW());

-- Insert 24 hours of sensor data for C-05
INSERT INTO sensor_readings (bathroom_id, sensor_type, gas_type, value, unit, created_at) VALUES
('C-05', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '23 hours'),
('C-05', 'water', NULL, 85, '%', NOW() - INTERVAL '23 hours'),
('C-05', 'humidity', NULL, 45, '%', NOW() - INTERVAL '23 hours'),
('C-05', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '22 hours'),
('C-05', 'water', NULL, 82, '%', NOW() - INTERVAL '22 hours'),
('C-05', 'humidity', NULL, 48, '%', NOW() - INTERVAL '22 hours'),
('C-05', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '21 hours'),
('C-05', 'water', NULL, 80, '%', NOW() - INTERVAL '21 hours'),
('C-05', 'humidity', NULL, 52, '%', NOW() - INTERVAL '21 hours'),
('C-05', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '20 hours'),
('C-05', 'water', NULL, 78, '%', NOW() - INTERVAL '20 hours'),
('C-05', 'humidity', NULL, 55, '%', NOW() - INTERVAL '20 hours'),
('C-05', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '19 hours'),
('C-05', 'water', NULL, 75, '%', NOW() - INTERVAL '19 hours'),
('C-05', 'humidity', NULL, 58, '%', NOW() - INTERVAL '19 hours'),
('C-05', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '18 hours'),
('C-05', 'water', NULL, 88, '%', NOW() - INTERVAL '18 hours'),
('C-05', 'humidity', NULL, 50, '%', NOW() - INTERVAL '18 hours'),
('C-05', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '17 hours'),
('C-05', 'water', NULL, 92, '%', NOW() - INTERVAL '17 hours'),
('C-05', 'humidity', NULL, 48, '%', NOW() - INTERVAL '17 hours'),
('C-05', 'gas', 'H2S', 30, '%', NOW() - INTERVAL '16 hours'),
('C-05', 'water', NULL, 95, '%', NOW() - INTERVAL '16 hours'),
('C-05', 'humidity', NULL, 45, '%', NOW() - INTERVAL '16 hours'),
('C-05', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '15 hours'),
('C-05', 'water', NULL, 90, '%', NOW() - INTERVAL '15 hours'),
('C-05', 'humidity', NULL, 42, '%', NOW() - INTERVAL '15 hours'),
('C-05', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '14 hours'),
('C-05', 'water', NULL, 88, '%', NOW() - INTERVAL '14 hours'),
('C-05', 'humidity', NULL, 40, '%', NOW() - INTERVAL '14 hours'),
('C-05', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '13 hours'),
('C-05', 'water', NULL, 85, '%', NOW() - INTERVAL '13 hours'),
('C-05', 'humidity', NULL, 38, '%', NOW() - INTERVAL '13 hours'),
('C-05', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '12 hours'),
('C-05', 'water', NULL, 82, '%', NOW() - INTERVAL '12 hours'),
('C-05', 'humidity', NULL, 35, '%', NOW() - INTERVAL '12 hours'),
('C-05', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '11 hours'),
('C-05', 'water', NULL, 80, '%', NOW() - INTERVAL '11 hours'),
('C-05', 'humidity', NULL, 32, '%', NOW() - INTERVAL '11 hours'),
('C-05', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '10 hours'),
('C-05', 'water', NULL, 78, '%', NOW() - INTERVAL '10 hours'),
('C-05', 'humidity', NULL, 30, '%', NOW() - INTERVAL '10 hours'),
('C-05', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '9 hours'),
('C-05', 'water', NULL, 75, '%', NOW() - INTERVAL '9 hours'),
('C-05', 'humidity', NULL, 28, '%', NOW() - INTERVAL '9 hours'),
('C-05', 'gas', 'H2S', 10, '%', NOW() - INTERVAL '8 hours'),
('C-05', 'water', NULL, 72, '%', NOW() - INTERVAL '8 hours'),
('C-05', 'humidity', NULL, 30, '%', NOW() - INTERVAL '8 hours'),
('C-05', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '7 hours'),
('C-05', 'water', NULL, 70, '%', NOW() - INTERVAL '7 hours'),
('C-05', 'humidity', NULL, 32, '%', NOW() - INTERVAL '7 hours'),
('C-05', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '6 hours'),
('C-05', 'water', NULL, 75, '%', NOW() - INTERVAL '6 hours'),
('C-05', 'humidity', NULL, 35, '%', NOW() - INTERVAL '6 hours'),
('C-05', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '5 hours'),
('C-05', 'water', NULL, 80, '%', NOW() - INTERVAL '5 hours'),
('C-05', 'humidity', NULL, 38, '%', NOW() - INTERVAL '5 hours'),
('C-05', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '4 hours'),
('C-05', 'water', NULL, 85, '%', NOW() - INTERVAL '4 hours'),
('C-05', 'humidity', NULL, 42, '%', NOW() - INTERVAL '4 hours'),
('C-05', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '3 hours'),
('C-05', 'water', NULL, 88, '%', NOW() - INTERVAL '3 hours'),
('C-05', 'humidity', NULL, 45, '%', NOW() - INTERVAL '3 hours'),
('C-05', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '2 hours'),
('C-05', 'water', NULL, 90, '%', NOW() - INTERVAL '2 hours'),
('C-05', 'humidity', NULL, 48, '%', NOW() - INTERVAL '2 hours'),
('C-05', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '1 hour'),
('C-05', 'water', NULL, 85, '%', NOW() - INTERVAL '1 hour'),
('C-05', 'humidity', NULL, 50, '%', NOW() - INTERVAL '1 hour'),
('C-05', 'gas', 'H2S', 30, '%', NOW()),
('C-05', 'water', NULL, 82, '%', NOW()),
('C-05', 'humidity', NULL, 52, '%', NOW());

-- Insert 24 hours of sensor data for D-06
INSERT INTO sensor_readings (bathroom_id, sensor_type, gas_type, value, unit, created_at) VALUES
('D-06', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '23 hours'),
('D-06', 'water', NULL, 85, '%', NOW() - INTERVAL '23 hours'),
('D-06', 'humidity', NULL, 45, '%', NOW() - INTERVAL '23 hours'),
('D-06', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '22 hours'),
('D-06', 'water', NULL, 82, '%', NOW() - INTERVAL '22 hours'),
('D-06', 'humidity', NULL, 48, '%', NOW() - INTERVAL '22 hours'),
('D-06', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '21 hours'),
('D-06', 'water', NULL, 80, '%', NOW() - INTERVAL '21 hours'),
('D-06', 'humidity', NULL, 52, '%', NOW() - INTERVAL '21 hours'),
('D-06', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '20 hours'),
('D-06', 'water', NULL, 78, '%', NOW() - INTERVAL '20 hours'),
('D-06', 'humidity', NULL, 55, '%', NOW() - INTERVAL '20 hours'),
('D-06', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '19 hours'),
('D-06', 'water', NULL, 75, '%', NOW() - INTERVAL '19 hours'),
('D-06', 'humidity', NULL, 58, '%', NOW() - INTERVAL '19 hours'),
('D-06', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '18 hours'),
('D-06', 'water', NULL, 88, '%', NOW() - INTERVAL '18 hours'),
('D-06', 'humidity', NULL, 50, '%', NOW() - INTERVAL '18 hours'),
('D-06', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '17 hours'),
('D-06', 'water', NULL, 92, '%', NOW() - INTERVAL '17 hours'),
('D-06', 'humidity', NULL, 48, '%', NOW() - INTERVAL '17 hours'),
('D-06', 'gas', 'H2S', 30, '%', NOW() - INTERVAL '16 hours'),
('D-06', 'water', NULL, 95, '%', NOW() - INTERVAL '16 hours'),
('D-06', 'humidity', NULL, 45, '%', NOW() - INTERVAL '16 hours'),
('D-06', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '15 hours'),
('D-06', 'water', NULL, 90, '%', NOW() - INTERVAL '15 hours'),
('D-06', 'humidity', NULL, 42, '%', NOW() - INTERVAL '15 hours'),
('D-06', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '14 hours'),
('D-06', 'water', NULL, 88, '%', NOW() - INTERVAL '14 hours'),
('D-06', 'humidity', NULL, 40, '%', NOW() - INTERVAL '14 hours'),
('D-06', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '13 hours'),
('D-06', 'water', NULL, 85, '%', NOW() - INTERVAL '13 hours'),
('D-06', 'humidity', NULL, 38, '%', NOW() - INTERVAL '13 hours'),
('D-06', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '12 hours'),
('D-06', 'water', NULL, 82, '%', NOW() - INTERVAL '12 hours'),
('D-06', 'humidity', NULL, 35, '%', NOW() - INTERVAL '12 hours'),
('D-06', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '11 hours'),
('D-06', 'water', NULL, 80, '%', NOW() - INTERVAL '11 hours'),
('D-06', 'humidity', NULL, 32, '%', NOW() - INTERVAL '11 hours'),
('D-06', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '10 hours'),
('D-06', 'water', NULL, 78, '%', NOW() - INTERVAL '10 hours'),
('D-06', 'humidity', NULL, 30, '%', NOW() - INTERVAL '10 hours'),
('D-06', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '9 hours'),
('D-06', 'water', NULL, 75, '%', NOW() - INTERVAL '9 hours'),
('D-06', 'humidity', NULL, 28, '%', NOW() - INTERVAL '9 hours'),
('D-06', 'gas', 'H2S', 10, '%', NOW() - INTERVAL '8 hours'),
('D-06', 'water', NULL, 72, '%', NOW() - INTERVAL '8 hours'),
('D-06', 'humidity', NULL, 30, '%', NOW() - INTERVAL '8 hours'),
('D-06', 'gas', 'H2S', 12, '%', NOW() - INTERVAL '7 hours'),
('D-06', 'water', NULL, 70, '%', NOW() - INTERVAL '7 hours'),
('D-06', 'humidity', NULL, 32, '%', NOW() - INTERVAL '7 hours'),
('D-06', 'gas', 'H2S', 15, '%', NOW() - INTERVAL '6 hours'),
('D-06', 'water', NULL, 75, '%', NOW() - INTERVAL '6 hours'),
('D-06', 'humidity', NULL, 35, '%', NOW() - INTERVAL '6 hours'),
('D-06', 'gas', 'H2S', 18, '%', NOW() - INTERVAL '5 hours'),
('D-06', 'water', NULL, 80, '%', NOW() - INTERVAL '5 hours'),
('D-06', 'humidity', NULL, 38, '%', NOW() - INTERVAL '5 hours'),
('D-06', 'gas', 'H2S', 20, '%', NOW() - INTERVAL '4 hours'),
('D-06', 'water', NULL, 85, '%', NOW() - INTERVAL '4 hours'),
('D-06', 'humidity', NULL, 42, '%', NOW() - INTERVAL '4 hours'),
('D-06', 'gas', 'H2S', 22, '%', NOW() - INTERVAL '3 hours'),
('D-06', 'water', NULL, 88, '%', NOW() - INTERVAL '3 hours'),
('D-06', 'humidity', NULL, 45, '%', NOW() - INTERVAL '3 hours'),
('D-06', 'gas', 'H2S', 25, '%', NOW() - INTERVAL '2 hours'),
('D-06', 'water', NULL, 90, '%', NOW() - INTERVAL '2 hours'),
('D-06', 'humidity', NULL, 48, '%', NOW() - INTERVAL '2 hours'),
('D-06', 'gas', 'H2S', 28, '%', NOW() - INTERVAL '1 hour'),
('D-06', 'water', NULL, 85, '%', NOW() - INTERVAL '1 hour'),
('D-06', 'humidity', NULL, 50, '%', NOW() - INTERVAL '1 hour'),
('D-06', 'gas', 'H2S', 30, '%', NOW()),
('D-06', 'water', NULL, 82, '%', NOW()),
('D-06', 'humidity', NULL, 52, '%', NOW());

COMMIT;

-- Verification queries (run these after the INSERT to verify data was inserted)
-- Uncomment to check:
-- SELECT bathroom_id, sensor_type, COUNT(*) as count 
-- FROM sensor_readings 
-- WHERE bathroom_id IN ('A-03', 'A-11', 'C-05', 'D-06')
-- AND created_at >= (NOW() - INTERVAL '24 hours')
-- GROUP BY bathroom_id, sensor_type
-- ORDER BY bathroom_id, sensor_type;

-- Expected result: Each bathroom should have 24 gas, 24 water, 24 humidity = 72 total per bathroom
